# 说明：
# 1) 复制本文件到：`src/main/resources/application-local.yml`
# 2) 使用 local 环境启动：
#    `./mvnw spring-boot:run -Dspring-boot.run.profiles=local`
#
# 依赖：
# - MySQL: 3306
# - Redis: 6379

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vegetable_forum?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379

security:
  jwt:
    issuer: vegetable-forum
    secret: 请修改为安全的随机字符串
    expire-seconds: 86400
  admin:
    user-ids:
      - 1

minio:
  enabled: true
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: vegetable-forum
  auto-create-bucket: true
  presign-expire-seconds: 3600

id:
  snowflake:
    worker-id: 1
    datacenter-id: 1
